'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8009
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class PRG_FIN_RECEIPT_UPLOAD

    '''<summary>
    '''PRG_FIN_RECEIPT_UPLOAD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PRG_FIN_RECEIPT_UPLOAD As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''litMsgs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litMsgs As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Status As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SB_CONT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SB_CONT As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''SB_DIV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SB_DIV As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''SB_MSG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SB_MSG As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblBatchNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBatchNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtBatchNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBatchNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkData_Source control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkData_Source As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblData_Source control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblData_Source As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboData_Source control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboData_Source As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtData_Source_SW control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtData_Source_SW As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtData_Source_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtData_Source_Name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_File_Upload0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_File_Upload0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''My_File_Upload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents My_File_Upload As Global.System.Web.UI.HtmlControls.HtmlInputFile

    '''<summary>
    '''txtFile_Upload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFile_Upload As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cmdFile_Upload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdFile_Upload As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblFile_Upload_Warning control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFile_Upload_Warning As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblXLS_Data_Start_No control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblXLS_Data_Start_No As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtXLS_Data_Start_No control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtXLS_Data_Start_No As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblXLS_Data_End_No control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblXLS_Data_End_No As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtXLS_Data_End_No control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtXLS_Data_End_No As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblXLS_Data_Remarks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblXLS_Data_Remarks As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblErr_List control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErr_List As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboErr_List control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboErr_List As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''grdUpldRecords control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdUpldRecords As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblResult As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRecptNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRecptNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''butPrintReceipt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents butPrintReceipt As Global.System.Web.UI.WebControls.Button
End Class
